### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by HoangMinhTuan-ops**
Hello Teachers,

my second homework of the Base Page, please take a look and leave feedbacks

Thank you

Tuan

### CODE REVIEW

**Review by MrTim — CHANGES_REQUESTED** [review]
I see that you just copied the example from Travis. This is not acceptable.
Please create your own page and try not to copy stuff.

And again - description is missleading. This homework is from lesson 1. We asked everyone to name the homeworks and branches properly. It's better for you (as a practice) and for teacher for understanding what this PR is about.

**Comment by HoangMinhTuan-ops** [comment]
Hello teacher,

thank you for your feedback. At the beginning, I understood that students should follow the demo website from teacher Travis, that is why I wrote at the footer is clone, I do not have any source code from teacher Travis to copy it and of course I do not even have any thought of copy stuff from any one. I think this is a misunderstood. For example, student are learning to put dotted border, is it couted as copy? If yes, I will get rid of it right away because I am just a student and I am trying to learn from teachers. I hope this not commiting any illegal.

**Comment by MrTim** [comment]
No worries! What I mean in previous comment - that from outside it looks like the plain copy, which was not intended to be the homework. Now I understood your logic, thx for explaining! From the students we want this page to be more personal, so we get to know each other.
Here is an explanation about homework (just in case) - https://mrtim.github.io/js-munich-2020-spring/homework/1_base_page
So please adjust the page so it would be your own places and would be nice if you'll try to style it in the way you like it.

**Comment by HoangMinhTuan-ops** [comment]
Thank you teacher, I am trying to create the new one, I am also very scare of copying without understanding, and also the copyright issue. Thank you for your explanation!

**Comment by MrTim** [comment]
Don't worry too much about it. If you want to copy - totally fine! Because maybe you would use it for future reference. 
About understanding - if you have question - just reach out to any teachers in MS Teams (as direct message or in general channels) and we will try to handle all your questions. This is a hard learning process so it's nothing wrong to not understand something and ask questions about it. We are here to help students!

**Comment by HoangMinhTuan-ops** [comment]
I find that teachers and collaborators in ReDi are really helpful and use all means to support students and I appreciate that. Thank you!

**Pull request merged**
